apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "73.1.0"
    chart: kube-prometheus-stack
    helm:
      valueFiles:
      - $values/app-of-apps/deploy-on/values/prometheus.yaml
  - repoURL: 'https://github.com/romanvianna/kubernetes-estudos.git'
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    # automated:
    #   prune: true
    #   allowEmpty: true
    #   selfHeal: true